version: '2'
services:
  web:
    image: fpfis/httpd-php-dev:7.3
    working_dir: ${PWD}
    ports:
      - 80:80
    volumes:
      - ${PWD}:${PWD} # Non Mac users.
#      - ./resources/.htaccess:${PWD}/web/.htaccess
#      - ./resources/.htpasswd:/etc/apache2/.htpasswd
    environment:
      # ASDA CREDENTIALS
      # By leaving these variables empty Docker Compose will set them to their host values.
      ASDA_USER:
      ASDA_PASSWORD:
      DOCUMENT_ROOT: ${PWD}/web
      HTTP_PORT: 80
      # XDEBUG CONFIGURATION
      # XDEBUG_CONFIG: "remote_enable=1 remote_host=172.17.0.1 remote_port=9000 idekey=PHPSTORM remote_autostart=1"
      # PHP_IDE_CONFIG: "serverName=Docker"
      # For Xdebug setup, run this command in the terminal:
      # For Mac users: sudo ifconfig en0 alias 172.17.0.1 255.255.255.0
      # For Linux users: sudo ip addr add 172.17.0.1/32 dev lo label lo:1
    env_file:
      - .env

  mysql:
    image: percona/percona-server:5.7
    command: --max_allowed_packet=1073741824
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./data/db/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: $DRUPAL_DATABASE_HOST
      PMA_USER: $DRUPAL_DATABASE_USERNAME
      PMA_PASSWORD: $DRUPAL_DATABASE_PASSWORD
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 10000
    ports:
      - 8080:80
    links:
      - mysql
